# Generated by Django 5.0.4 on 2024-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogapp", "0001_added_document_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="identifier",
            field=models.CharField(default=None, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="url",
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
